apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-per-vc
  labels:
    app: wordpress-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:  
    requests:
      storage: 20Gi
      

