apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-per-vc
  labels:
    app: wordpress-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:  
    requests:
      storage: 20Gi
      
      -=-=-=-=-=-=-=-=-=-=-=-=-=-=-
      
      apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpress-rs
  labels:
    app: wp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wp-deployment
      tier: frontend
  template:
    metadata:
      labels:
        app: wp-deployment
        tier: frontend
    spec:
      containers:
      - image: wordpress:5.0-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-wp
        - name: WORDPRESS_DB_PASSWORD
          value: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: worldpress-pvc
          
          -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
          
          
        apiVersion: v1
kind: LB-Service
metadata:
  labels:
    app: wp-deployment
  name: wordpress-service
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-deployment
  sessionAffinity: None
  type: LoadBalancer
